name: Detect Secrets

# Run on all branches, not just main/master
on:
  push:
    branches: [ '**' ]  # Match all branches
  pull_request:
  # Optional: Allow manual triggering
  workflow_dispatch:

jobs:
  gitleaks:
    name: Detect Secrets with Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for proper scanning
      
      - name: Add commit metadata
        run: |
          echo "Scan initiated at 2025-06-29 20:46:06 UTC"
          echo "Repository: ${{ github.repository }}"
          echo "Triggered by: ahmadasjad"
          echo "Scanning all commits on branch ${{ github.ref_name }}"
      
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # The workflow will fail if Gitleaks finds secrets

  trufflehog:
    name: TruffleHog Secret Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for proper scanning
      
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          # Scan everything, not just changes from default branch
          extra_args: --debug --only-verified
