name: Summarize PRs with AI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      models: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AI inference
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Analyze the following GitHub Pull Request and write a concise, clear summary.
            Keep the response **under 50 lines**.
            Write as much or as little as needed to accurately summarize the change — it can be 5 lines or 40, but do not exceed 50 lines.

            ---
            Title: ${{ github.event.pull_request.title }}
            Body: ${{ github.event.pull_request.body }}

      - name: Comment with AI summary
        run: |
          gh pr comment $PR_NUMBER --body '${{ steps.inference.outputs.response }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
